name: Deploy
on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 51.75.16.226 >> ~/.ssh/known_hosts
      - name: Test SSH Connection
        run: ssh -i ~/.ssh/id_rsa debian@51.75.16.226 "echo Connected!"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build again (optional if artifacts not passed)
        run: |
          npm install
          npm run build

      - name: Deploy to server
        run: |
          rsync -avz ./build/ user@your.server.com:/var/www/my-app/

