# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    defaults:
      run:
        working-directory: ApiPlateforme
    steps:
    - uses: actions/checkout@v4
    - run: ls
    - run: npm i
    - run: npm run build --if-present
    - run: ls ./dist
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
       name: build-artifacts
       path: dist/**/*
       
  deploy:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest
      steps:
        - name: Set up SSH key
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_SECRET }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H 51.75.16.226 >> ~/.ssh/known_hosts
        - name: Output of the id_rsa file
          run : cat ~/.ssh/id_rsa
        - name: Download build artifact
          uses: actions/download-artifact@v4
          with:
            name: build-artifacts   # doit correspondre exactement au nom utilisé à l'upload
            path: ./dist     # là où tu veux que l'artifact soit extrait
        - name: Install sshpass and connect
          run: |
            sudo apt-get update && sudo apt-get install -y sshpass
            sshpass -p "6Z)R7N£o4W0%" ssh -o StrictHostKeyChecking=no debian@51.75.16.226 "echo Connected!"
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Deploy to server
          run: |
            sshpass -p "6Z)R7N£o4W0%" rsync -avz ./dist/ debian@51.75.16.226:/home/debian/
