# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    defaults:
      run:
        working-directory: ApiPlateforme
    steps:
    - uses: actions/checkout@v4
    - run: ls
    - run: npm i
    - run: npm run build --if-present
    - run: ls ./dist
    - name: Deploy to server
      run: |
        sudo apt-get update && sudo apt-get install -y sshpass rsync
        sshpass -p "6Z)R7N£o4W0%" ssh -o StrictHostKeyChecking=no debian@51.75.16.226 "echo Connected!"
        sshpass -p "6Z)R7N£o4W0%" rsync -avz ./dist/ debian@51.75.16.226:/home/debian/

